### ISSUE TITLE
user 도메인 개발

### ISSUE THREAD

**Issue by d36choi** [dnd-side-project/dnd-5th-10-backend#12]

**Comment by d36choi** [comment]
@RulLu16 
password 빼버릴까영

**Comment by RulLu16** [comment]
> @RulLu16
> password 빼버릴까영

넵. 필요없을거같아요!

**Comment by RulLu16** [comment]
혹시 userservice interface, impl 따로 나눈 이유가 있나요??

**Comment by d36choi** [comment]
https://akdl911215.tistory.com/281
https://itzjamie96.github.io/2021/01/24/spring-service-and-serviceimpl/

이런 이유가 있는거고 어느 정도 관례적으로 저는 저렇게 해요.
근데 이런 토이프로젝트에서는 인터페이스 하나당 구현체가 하나니까
솔직히 별의미는 없을 수 있어요..

하지만 만약 요구사항이 지속적으로 바뀌게 된다면
재사용과 교체가 자주 일어날거고 그때는 밥값을 할 수도 있겠죠?
ㅋㅋ

2021년 7월 26일 (월) 오후 10:14, YeEun Lee ***@***.***>님이 작성:

**Comment by RulLu16** [comment]
오옹 그렇군요! ㅋㅋㅋ 그럼 저도 저렇게 해볼게요!
