### ISSUE TITLE
entity 클래스 정의 및 연결 방향 설정

### ISSUE THREAD

**Issue by RulLu16** [dnd-side-project/dnd-5th-10-backend#4]
이번 주에 와이어프레임 나오고, 세부 기능까지 완료되면 DB 필드까지 완성해서 클래스 설정합시당!
각각 단방향으로 할지 양방향으로 할지는, 개발하다가 필요하면 추가해도 될 것 같은데, 아니면 미리 방향까지 설정하고 들어가야 할까요?

그리고 패키지를 어떻게 나누는게 좋으신가요?? controller, service끼리 묶는게 좋은지, 아니면 문제끼리, 북마크끼리 등등으로 묶는게 좋은지 궁금합니다~!

**Comment by d36choi** [comment]
단방향 기본 -> 만들면서 필요시 양방향으로 가면 좋을 것 같아요. 김영한님의 글을 옮겨놓은 블로그 글입니다.
[참고](https://jeong-pro.tistory.com/231)
패키지 나누는건... 정답은 없는 것 같아요. 뭐가 편하세요?

**Comment by RulLu16** [comment]
> 단방향 기본 -> 만들면서 필요시 양방향으로 가면 좋을 것 같아요. 김영한님의 글을 옮겨놓은 블로그 글입니다.
> [참고](https://jeong-pro.tistory.com/231)
> 패키지 나누는건... 정답은 없는 것 같아요. 뭐가 편하세요?

음.. 저도 사실 상관은 없습니다 ㅋㅋ 둘다 장단점이 있다보니.. 혹시 선호하시는 스타일이 있을까요? 아니면 사다리 탈까요? ㅎㅎ

**Comment by d36choi** [comment]
저는 그냥 mvc패턴대로 Repository, Service, Controller, Domain 패키지로 먼저 나눠요
제가 클래스찾을 때 패키지를 막 타고들어가지는 않아서 ㅋㅎ
비슷한 느낌 찾아봤어요 
[썜플](https://github.com/bigzidane/springboot-rest-h2-swagger/tree/master/src/main/java/com/es/challenge)

**Comment by RulLu16** [comment]
넵 그럼 그렇게 나누죠!! 좋습니당~!

**Comment by d36choi** [comment]
[oauth2 관련 erd](https://www.erdcloud.com/d/7Gqsb4z2Do6WrqGKh)
